# N Grams

Bigram : two combination

Trigram: Three Combination

sklearn-> n-gram(1,1)-> unigram<br>
sklearn->n-gram(1,2) -> unigram,bigram<br>
sklearn->n-gram(1,3)-> unigram,bigram,trigram<br>
sklearn->n-gram(2,3)-> bigram ,trigram<br>

# implementation

In [1]:
import pandas as pd 

df=pd.read_csv('spam.csv',encoding='latin1')
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [2]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [3]:
df=df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
# change columns names
df.columns=['label','text']
df

label                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.shape

(5572, 2)

In [6]:
# Data cleaning and Preprocessing
import nltk
import re

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\PC/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [8]:
df['text']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: text, Length: 5572, dtype: object

In [9]:
corpus=[]
for i in range(len(df)):
    review=re.sub('[^a-zA-Z]',' ',df['text'][i])
    review=review.lower()
    review=review.split() # converting to list each word to apply stemming on each word we can also use word_tokenize in it
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)  # converting list to string
    corpus.append(review)

In [23]:
## create bag of words 
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True) # take the top 2500 words which has greater frequency
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 100))

In [24]:
X.shape

(5572, 100)

#N-Grams

In [25]:
cv.vocabulary_ # dict of top 2500 words 

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(90),
 'ok': np.int64(56),
 'free': np.int64(18),
 'win': np.int64(94),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(67),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(73),
 'send': np.int64(69),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(62),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(47),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(82),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(64),
 'www': np.int64(96),
 'right': np.int64(65),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'use': np.int64(87),
 'messag': np.int64(44),
 'oh': np.int64(55),
 'ye': np.int64(97),
 'make': np.int64(42),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(14

In [27]:
## create bag of words with n-grams
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(1,1)) # take the top 2500 words which has greater frequency with (1,1) nohting will change as its default 
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 100))

In [33]:
## create bag of words with n-grams
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500,binary=True,ngram_range=(1,2)) # take the top 2500 words which has greater frequency with unigram and bigram
X=cv.fit_transform(corpus).toarray()
X,X.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 500)),
 (5572, 500))

In [31]:
cv.vocabulary_


{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(91),
 'ok': np.int64(57),
 'free': np.int64(18),
 'win': np.int64(95),
 'text': np.int64(78),
 'txt': np.int64(86),
 'say': np.int64(68),
 'alreadi': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(28),
 'week': np.int64(93),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(74),
 'send': np.int64(70),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(63),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(48),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(90),
 'today': np.int64(83),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(65),
 'www': np.int64(97),
 'right': np.int64(66),
 'thank': np.int64(79),
 'take': np.int64(76),
 'time': np.int64(82),
 'use': np.int64(88),
 'messag': np.int64(45),
 'oh': np.int64(56),
 'ye': np.int64(98),
 'make': np.int64(43),
 'way': np.int64(92),
 'feel': np.int64(16),
 'dont': np.int64(14

In [34]:
## create bag of words with n-grams
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500,binary=True,ngram_range=(2,2)) # take the top 2500 words which has greater frequency with   bigram
X=cv.fit_transform(corpus).toarray()
X,X.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 500)),
 (5572, 500))

In [35]:
cv.vocabulary_

{'free entri': np.int64(127),
 'rate appli': np.int64(328),
 'per request': np.int64(300),
 'claim call': np.int64(54),
 'call claim': np.int64(24),
 'claim code': np.int64(55),
 'entitl updat': np.int64(113),
 'updat latest': np.int64(431),
 'latest colour': np.int64(211),
 'free call': np.int64(125),
 'call mobil': np.int64(32),
 'mobil updat': np.int64(261),
 'chanc win': np.int64(53),
 'win cash': np.int64(474),
 'repli hl': np.int64(336),
 'hl info': np.int64(185),
 'txt word': np.int64(426),
 'dont miss': np.int64(102),
 'let know': np.int64(218),
 'feel like': np.int64(118),
 'yeah got': np.int64(497),
 'tell anyth': np.int64(394),
 'mobil charg': np.int64(256),
 'repli ye': np.int64(338),
 'go home': np.int64(148),
 'anyth lor': np.int64(3),
 'call repli': np.int64(36),
 'nokia mobil': np.int64(280),
 'mobil free': np.int64(258),
 'free camcord': np.int64(126),
 'pleas call': np.int64(310),
 'deliveri tomorrow': np.int64(96),
 'lt gt': np.int64(234),
 'miss call': np.int64(253)

In [36]:
## create bag of words with n-grams
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500,binary=True,ngram_range=(3,3)) # take the top 2500 words which has greater frequency with   bigram
X=cv.fit_transform(corpus).toarray()
X,X.shape,cv.vocabulary_

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 500)),
 (5572, 500),
 {'free entri wkli': np.int64(138),
  'std txt rate': np.int64(385),
  'txt rate appli': np.int64(415),
  'set callertun caller': np.int64(350),
  'callertun caller press': np.int64(44),
  'caller press copi': np.int64(42),
  'press copi friend': np.int64(313),
  'copi friend callertun': np.int64(88),
  'call claim code': np.int64(26),
  'entitl updat latest': np.int64(110),
  'updat latest colour': np.int64(427),
  'free call mobil': np.int64(133),
  'call mobil updat': np.int64(34),
  'mobil updat co': np.int64(247),
  'updat co free': np.int64(426),
  'chanc win cash': np.int64(61),
  'repli hl info': np.int64(331),
  'like lt gt': np.int64(194),
  'bx ip pm': np.int64(24),
  'sorri call later': np.int64(373),
  'call later meet': np.int64(3

start with (1,1) if not getting good accuracy increase to (1,2) then (1,3) etc hyperparameter